FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY fpl-web-1.0.jar /app/app.jar
COPY config.yml /app/config.yml
EXPOSE 8080
USER 65534:65534
ENTRYPOINT ["java", "-jar", "/app/app.jar", "server", "/app/config.yml"]
